import express from 'express';
import authenticationToken from '../../middleware/auth/authenticationToken.middleware';
import globalValidator from '../../utils/globalValidator';
import { reviewValidationSchema } from '../../utils/validator';
import createReview from '../../service/impl/review/createReview/createReview.impl';
import showReviews from '../../service/impl/review/showReviews/showReviews.impl';
import showReview from '../../service/impl/review/showReview/showReview.impl';
const router = express.Router();
router.post('/create-review', authenticationToken, globalValidator(reviewValidationSchema), createReview);
router.get('/show-reviews', authenticationToken, showReviews);
router.get('/show-review/:id', authenticationToken, showReview);
export default router;