import express from 'express';
import authenticationToken from '../../middleware/auth/authenticationToken.middleware';
import createProduct from '../../service/impl/product/createProduct/createProduct.impl';
import globalValidator from '../../utils/globalValidator';
import { productValidationSchema } from '../../utils/validator';
import showProducts from '../../service/impl/product/showProducts/showProducts.impl';
const router = express.Router();
router.post('/create-product', authenticationToken, globalValidator(productValidationSchema), createProduct);
router.get('/show-products', authenticationToken, showProducts);
export default router;