import express from 'express';
import authenticationToken from '../../middleware/auth/authenticationToken.middleware';
import createOrder from '../../service/impl/order/createOrder/createOrder.impl';
import globalValidator from '../../utils/globalValidator';
import { orderValidationSchema, updateOrderValidationSchema } from '../../utils/validator';
import showOrders from '../../service/impl/order/showOrders/showOrders.impl';
import showOrder from '../../service/impl/order/showOrder/showOrder.impl';
import updateOrder from '../../service/impl/order/updateOrder/updateOrder.impl';
const router = express.Router();
router.post('/create-order', authenticationToken, globalValidator(orderValidationSchema), createOrder);
router.get('/show-orders', authenticationToken, showOrders);
router.get('/show-order/:id', authenticationToken, showOrder);
router.put('/update-order/:id', authenticationToken, globalValidator(updateOrderValidationSchema), updateOrder);
export default router;