import express from 'express';
import authenticationToken from '../../middleware/auth/authenticationToken.middleware';
import globalValidator from '../../utils/globalValidator';
import { categoryValidationSchema, updateCategoryValidationSchema } from '../../utils/validator';
import createCategory from '../../service/impl/category/createCategory/createCategory.impl';
import showCategories from '../../service/impl/category/showCategories/showCategories.impl';
import showCategory from '../../service/impl/category/showCategory/showCategory.impl';
import updateCategory from '../../service/impl/category/updateCategory/updateCategory.impl';
import deleteCategory from '../../service/impl/category/deleteCategory/deleteCategory.impl';
const router = express.Router();
router.post('/create-category', authenticationToken, globalValidator(categoryValidationSchema), createCategory);
router.get('/show-categories', authenticationToken, showCategories);
router.get('/show-category/:id', authenticationToken, showCategory);
router.put('/update-category/:id', authenticationToken, globalValidator(updateCategoryValidationSchema), updateCategory);
router.delete('/delete-category/:id', authenticationToken, deleteCategory);
export default router;